// Migration script to add new fields to existing users
const mongoose = require("mongoose");
require("dotenv").config();

const User = require("../models/User");

async function migrateUsers() {
  try {
    console.log("🔄 Starting user migration...");

    // Connect to database
    await mongoose.connect(process.env.MONGODB_URI);
    console.log("✅ Connected to database");

    // Get all users
    const users = await User.find({});
    console.log(`📊 Found ${users.length} users to migrate`);

    let updated = 0;

    for (const user of users) {
      let needsUpdate = false;

      // Add loyalty points if missing
      if (!user.loyaltyPoints) {
        user.loyaltyPoints = {
          balance: 0,
          totalEarned: 0,
          totalRedeemed: 0,
          tier: "bronze",
          lastUpdated: new Date(),
        };
        needsUpdate = true;
      }

      // Add referral stats if missing
      if (!user.referralStats) {
        user.referralStats = {
          totalReferrals: 0,
          successfulReferrals: 0,
          rewardsEarned: 0,
        };
        needsUpdate = true;
      }

      // Generate referral code if missing (only for regular users)
      if (!user.referralCode && user.role === "user") {
        // Will be generated by pre-save hook
        needsUpdate = true;
      }

      if (needsUpdate) {
        await user.save();
        updated++;
        console.log(`✅ Updated user: ${user.email}`);
      }
    }

    console.log(`\n🎉 Migration complete!`);
    console.log(`📊 Total users: ${users.length}`);
    console.log(`✅ Updated: ${updated}`);
    console.log(`⏭️  Skipped: ${users.length - updated}`);

    process.exit(0);
  } catch (error) {
    console.error("❌ Migration failed:", error);
    process.exit(1);
  }
}

// Run migration
migrateUsers();
